title: "Lee Atchison | Cloud Strategist, Thought Leader, Industry Cloud Expert"
theme: "airspace-hugo"
paginate: 10
summaryLength: 30
permalinks:
  atscale: /atscale/:year/:month/:day/:title/
  project: /classes/:title/
sitemap:
  changefreq: monthly
  priority: 0.5
enableRobotsTXT: true

taxonomies:
  category: categories
  tag: tags
