main:
  - name: "Topics & Content"
    URL: "/categories/article/"
    weight: 1
    hasChildren: true
  - name: "Articles"
    parent: "Topics & Content"
    URL: "/categories/article/"
    weight: 1
  - name: "Presentations"
    parent: "Topics & Content"
    URL: "/categories/presentation/"
    weight: 2
  - name: "Curated Lists"
    URL: "/lists/"
    weight: 2
    hasChildren: true
  - name: "Serverless"
    parent: "Curated Lists"
    URL: "/lists/serverless/"
    weight: 1
  - name: "Microservices"
    parent: "Curated Lists"
    URL: "/lists/services/"
    weight: 2
  - name: "Risk Management"
    parent: "Curated Lists"
    URL: "/lists/risk-management/"
    weight: 3
  - name: "Classes"
    URL: "/classes/"
    weight: 3
  - name: "Book"
    URL: "/architectingforscale/"
    weight: 4
  - name: "Lee@Scale"
    URL: "/atscale/"
    weight: 5
  - name: "Podcast"
    URL: "/mda/"
    weight: 6
footer:
  - name: "Media Info"
    URL: "/mediainfo/"
    weight: 1
  - name: "Contact Lee"
    URL: "/contact/"
    weight: 2
  - name: "Subscribe"
    URL: "/subscribe/"
    weight: 3
